# port: /dev/port3
port: /dev/ttyACM0
baud: 57600
timeout: 0.1

# rate: 150
rate:  20

base_frame: base_link

type: GP2Y0A21YK0F
angles: [-45, -25, -10, 0, 10, 25, 45, 155, 180, 205] # Goc bo tri senso, donvi: do
pins: [0,1,2,3,4,5,6,7,8,9] # Arduino Mega
sensor_rate: 20
result_rate: 5
